services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: whos-that-pokemon
    ports:
      - "3000:80"
    restart: unless-stopped
    environment:
      - NODE_ENV=production

